/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.CityDirectory;
import model.CommunityDirectory;

import model.HospitalDir;
import model.HospitalDirDirectory;
import model.HospitalDirectory;
import model.HouseDirectory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Ruchi Anand Sagar
 */
public class HospitalAdminDJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminDJPanel
     */
    PatientDirectory patientHistory;
    PersonDirectory personHistory;
    HouseDirectory houseHistory;
    CityDirectory cityHistory;
    HospitalDirectory hospitalHistory;
   CommunityDirectory communityHistory;
    HospitalDirDirectory hospitalDirHistory;
    public HospitalAdminDJPanel(PersonDirectory personHistory,PatientDirectory patientHistory,HouseDirectory houseHistory,CommunityDirectory communityHistory,  CityDirectory cityHistory,HospitalDirectory hospitalHistory,HospitalDirDirectory hospitalDirHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory=patientHistory;
        this.houseHistory=houseHistory;
        this.communityHistory=communityHistory;
        this.cityHistory=cityHistory;
        this.hospitalHistory=hospitalHistory;
        this.hospitalDirHistory=hospitalDirHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        viewbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        contactnocdoclbl = new javax.swing.JLabel();
        experiencecdoctxt = new javax.swing.JTextField();
        specialitycdoclbl = new javax.swing.JLabel();
        submitcdocbtn = new javax.swing.JButton();
        emailidcdoclbl = new javax.swing.JLabel();
        experiencecdoclbl = new javax.swing.JLabel();
        gendercdoclbl = new javax.swing.JLabel();
        namecdoctxt = new javax.swing.JTextField();
        gendercdoctxt = new javax.swing.JTextField();
        emailidcdoctxt = new javax.swing.JTextField();
        contactnocdoctxt = new javax.swing.JTextField();
        namecdoclbl = new javax.swing.JLabel();
        degreecdoctxt = new javax.swing.JTextField();
        degreecdoclbl = new javax.swing.JLabel();
        specialitycdoctxt = new javax.swing.JTextField();
        availabilitycdoclbl = new javax.swing.JLabel();
        availabilitycdoctxt = new javax.swing.JTextField();

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewbtn)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(viewbtn)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        contactnocdoclbl.setText("Contact No");

        specialitycdoclbl.setText("Speciality");

        submitcdocbtn.setText("Submit");
        submitcdocbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitcdocbtnActionPerformed(evt);
            }
        });

        emailidcdoclbl.setText("Email ID");

        experiencecdoclbl.setText("Experience");

        gendercdoclbl.setText("Gender");

        namecdoclbl.setText("Name");

        degreecdoclbl.setText("Degree");

        availabilitycdoclbl.setText("Availability");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(gendercdoctxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(namecdoctxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(namecdoclbl)
                                                .addComponent(gendercdoclbl))
                                            .addGap(265, 265, 265))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(emailidcdoctxt)
                                            .addGap(167, 167, 167)))
                                    .addComponent(emailidcdoclbl)
                                    .addComponent(contactnocdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactnocdoclbl))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availabilitycdoclbl)
                                    .addComponent(experiencecdoclbl)
                                    .addComponent(degreecdoclbl)
                                    .addComponent(degreecdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(specialitycdoclbl)
                                    .addComponent(specialitycdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(experiencecdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availabilitycdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(submitcdocbtn)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namecdoclbl)
                    .addComponent(degreecdoclbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namecdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreecdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialitycdoclbl)
                    .addComponent(gendercdoclbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gendercdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialitycdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailidcdoclbl)
                    .addComponent(experiencecdoclbl))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailidcdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(experiencecdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactnocdoclbl)
                    .addComponent(availabilitycdoclbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactnocdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availabilitycdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(submitcdocbtn)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitcdocbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitcdocbtnActionPerformed
        // TODO add your handling code here:
        String name= namecdoctxt.getText();

        String gender= gendercdoctxt.getText();
        String emailid= emailidcdoctxt.getText();
        long contactno= Long.parseLong(contactnocdoctxt.getText());
        String degree= degreecdoctxt.getText();
        String speciality= specialitycdoctxt.getText();
        String experience = (experiencecdoctxt.getText());

        HospitalDir hd =hospitalDirHistory.addNewHospitalDir();
        hd.setName(name);
        hd.setGender(gender);
        hd.setEmailid(emailid);
        hd.setContactno(contactno);
        hd.setDegree(degree);
        hd.setSpeciality(speciality);
        hd.setExperience(experience);
        JOptionPane.showMessageDialog(this, "Doctor Registered Successfully!!");

        namecdoctxt.setText("");
        gendercdoctxt.setText("");
        emailidcdoctxt.setText("");
        contactnocdoctxt.setText("");
        degreecdoctxt.setText("");
        specialitycdoctxt.setText("");
        experiencecdoctxt.setText("");
        availabilitycdoctxt.setText("");
    }//GEN-LAST:event_submitcdocbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
      
        ViewHospitalAdminDJPanel  viewHospitalAdminDJPanel=new ViewHospitalAdminDJPanel(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory);
        jSplitPane2.setRightComponent(viewHospitalAdminDJPanel);
        
        
    }//GEN-LAST:event_viewbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilitycdoclbl;
    private javax.swing.JTextField availabilitycdoctxt;
    private javax.swing.JLabel contactnocdoclbl;
    private javax.swing.JTextField contactnocdoctxt;
    private javax.swing.JLabel degreecdoclbl;
    private javax.swing.JTextField degreecdoctxt;
    private javax.swing.JLabel emailidcdoclbl;
    private javax.swing.JTextField emailidcdoctxt;
    private javax.swing.JLabel experiencecdoclbl;
    private javax.swing.JTextField experiencecdoctxt;
    private javax.swing.JLabel gendercdoclbl;
    private javax.swing.JTextField gendercdoctxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel namecdoclbl;
    private javax.swing.JTextField namecdoctxt;
    private javax.swing.JLabel specialitycdoclbl;
    private javax.swing.JTextField specialitycdoctxt;
    private javax.swing.JButton submitcdocbtn;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
