@startuml
annotation java.lang.Override
class model.Community
class model.Patient
class model.PatientDirectory
class model.Person
class model.PersonDirectory
model.Patient ..> java.lang.Override
model.PatientDirectory ..> model.Patient
model.Person ..> java.lang.Override
model.PersonDirectory ..> model.Person
@enduml