/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;


import model.HospitalDirDirectory;
import model.HospitalDirectory;

import model.HouseDirectory;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSignsHistory;

/**
 *
 * @author Ruchi Anand Sagar
 */
public class PatientJFrame extends javax.swing.JFrame {
    
    
    
    

    /**
     * Creates new form PatientJFrame
     */
    
    PatientDirectory patientHistory;
    PersonDirectory personHistory;
    HouseDirectory houseHistory;
    CommunityDirectory communityHistory;
    CityDirectory cityHistory;
    HospitalDirectory hospitalHistory;
    HospitalDirDirectory hospitalDirHistory;
    DoctorDirectory doctorHistory;
    EncounterHistory encounterHistory;
     VitalSignsHistory vitalSignsHistory;
    String maritalstatus;
    String insurance;
    
    public PatientJFrame( PersonDirectory personHistory,PatientDirectory patientHistory,HouseDirectory houseHistory,CommunityDirectory communityHistory,
    CityDirectory cityHistory,
    HospitalDirectory hospitalHistory,HospitalDirDirectory hospitalDirHistory,DoctorDirectory doctorHistory,EncounterHistory encounterHistory,VitalSignsHistory vitalSignsHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory=patientHistory;
        this.houseHistory=houseHistory;
        this.communityHistory=communityHistory;
        this.cityHistory=cityHistory;
        this.hospitalHistory=hospitalHistory;
        this.hospitalDirHistory=hospitalDirHistory;
        this.doctorHistory=doctorHistory;
        this.encounterHistory=encounterHistory;
        this.vitalSignsHistory=vitalSignsHistory;
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maritalstatusbtn = new javax.swing.ButtonGroup();
        insurancebtn = new javax.swing.ButtonGroup();
        namelblpat = new javax.swing.JLabel();
        agelblpat = new javax.swing.JLabel();
        genderlblpat = new javax.swing.JLabel();
        emailidlblpat = new javax.swing.JLabel();
        contactnolblpat = new javax.swing.JLabel();
        maritalstatuslblpat = new javax.swing.JLabel();
        insurancelblpat = new javax.swing.JLabel();
        allergieslblpat = new javax.swing.JLabel();
        allergiestxtpat = new javax.swing.JTextField();
        emergencylblpat = new javax.swing.JLabel();
        emergencytxtpat = new javax.swing.JTextField();
        medicalhistorylblpat = new javax.swing.JLabel();
        symptomslblpat = new javax.swing.JLabel();
        medicalhistorytxtpat = new javax.swing.JTextField();
        submitbtnpat = new javax.swing.JButton();
        backbtnpat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        singlebtn = new javax.swing.JRadioButton();
        marriedbtn = new javax.swing.JRadioButton();
        symptomscbox = new javax.swing.JComboBox<>();
        yesbtn = new javax.swing.JCheckBox();
        nobtn = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maritalstatuslblpat.setText("Marital Status");

        insurancelblpat.setText("Any Health Insurance?");

        allergieslblpat.setText("Any Allergies?");

        emergencylblpat.setText("Emergency Contact No");

        emergencytxtpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencytxtpatActionPerformed(evt);
            }
        });

        medicalhistorylblpat.setText("Medical History");

        symptomslblpat.setText("Symptoms");

        submitbtnpat.setText("Submit");
        submitbtnpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnpatActionPerformed(evt);
            }
        });

        backbtnpat.setText("<<");
        backbtnpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnpatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Person Details:");

        maritalstatusbtn.add(singlebtn);
        singlebtn.setText("Single");

        maritalstatusbtn.add(marriedbtn);
        marriedbtn.setText("Married");

        symptomscbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chills/Cold", "Fever", "Paresthesia", "Light-headed", "Short of breath", "Dizzy ", "Nauseated", "Cough", "Acidity" }));

        insurancebtn.add(yesbtn);
        yesbtn.setText("Yes");

        insurancebtn.add(nobtn);
        nobtn.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitbtnpat)
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backbtnpat)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailidlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactnolblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maritalstatuslblpat)
                            .addComponent(insurancelblpat)
                            .addComponent(allergieslblpat)
                            .addComponent(emergencylblpat)
                            .addComponent(medicalhistorylblpat)
                            .addComponent(symptomslblpat))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(singlebtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(marriedbtn))
                                .addComponent(symptomscbox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emergencytxtpat)
                                .addComponent(medicalhistorytxtpat)
                                .addComponent(allergiestxtpat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backbtnpat)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(namelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maritalstatuslblpat)
                                        .addComponent(singlebtn)
                                        .addComponent(marriedbtn))
                                    .addComponent(agelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(genderlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(emailidlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(insurancelblpat)
                                            .addComponent(yesbtn)
                                            .addComponent(nobtn))))
                                .addGap(33, 33, 33)
                                .addComponent(contactnolblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(allergieslblpat)
                            .addComponent(allergiestxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emergencylblpat)
                            .addComponent(emergencytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(medicalhistorylblpat))
                    .addComponent(medicalhistorytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomslblpat)
                    .addComponent(symptomscbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(submitbtnpat)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emergencytxtpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencytxtpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencytxtpatActionPerformed

    private void submitbtnpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnpatActionPerformed
        // TODO add your handling code here:
        String name= namelblpat.getName();
        int age= Integer.parseInt(agelblpat.getText());
        String gender= genderlblpat.getText();
        String emailid= emailidlblpat.getText();
        long contactno= Long.parseLong(contactnolblpat.getText());
        if(singlebtn.isSelected()==true)
        {
             maritalstatus = "Single";
        }
        if(marriedbtn.isSelected()==true)
        {
            maritalstatus = "Married";
        }
        if(yesbtn.isSelected()==true)
        {
             insurance = "Yes";
        }
        if(nobtn.isSelected()==true)
        {
            insurance = "No";
        }
        
        
        
        
        
        
         String allergies= allergiestxtpat.getText();
        long emergencycontact= Long.parseLong(emergencytxtpat.getText());
        String medicalhistory= medicalhistorytxtpat.getText();
        String symptoms=(String) symptomscbox.getSelectedItem();
        
        Patient pa =patientHistory.addNewPatient();
        pa.setName(name);
        pa.setAge(age);
        pa.setGender(gender);
        pa.setEmailid(emailid);
        pa.setContactno(contactno);
       
        pa.setMaritalstatus(maritalstatus);
        pa.setInsurance(insurance);
        pa.setAllergies(allergies);
        pa.setEmergencycontact(emergencycontact);
        pa.setMedicalhistory(medicalhistory);
        pa.setSymptoms(symptoms);
        JOptionPane.showMessageDialog(this, "Patient Registered Successfully!!");
        
       
  
        
        dispose();
        PatientHouseDetailsJFrame phd=new PatientHouseDetailsJFrame(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory,doctorHistory,encounterHistory,vitalSignsHistory);
        phd.namep.setText(namelblpat.getText());
        phd.agep.setText(agelblpat.getText());
        phd.genderp.setText(genderlblpat.getText());
        phd.emailidp.setText(emailidlblpat.getText());
        phd.contactnop.setText(contactnolblpat.getText());
        phd.maritalstatusp.setText(maritalstatus);
        phd.allergiesp.setText(allergiestxtpat.getText());
        phd.emergencycontactp.setText(emergencytxtpat.getText());
        phd.medhistp.setText(medicalhistorytxtpat.getText());
        phd.symptomsp.setText(symptoms);
        
        
        
        
        phd.setVisible(true);
        
       
        maritalstatusbtn.clearSelection();
        insurancebtn.clearSelection();
        allergiestxtpat.setText("");
        emergencytxtpat.setText("");
        medicalhistorytxtpat.setText("");
        symptomscbox.setSelectedIndex(-1);
    }//GEN-LAST:event_submitbtnpatActionPerformed

    private void backbtnpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnpatActionPerformed
        // TODO add your handling code here:
        dispose();
        SystemJFrame systemjframe=new SystemJFrame(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory,doctorHistory,encounterHistory,vitalSignsHistory);
            systemjframe.setVisible(true);
    }//GEN-LAST:event_backbtnpatActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel agelblpat;
    private javax.swing.JLabel allergieslblpat;
    private javax.swing.JTextField allergiestxtpat;
    private javax.swing.JButton backbtnpat;
    public javax.swing.JLabel contactnolblpat;
    public javax.swing.JLabel emailidlblpat;
    private javax.swing.JLabel emergencylblpat;
    private javax.swing.JTextField emergencytxtpat;
    public javax.swing.JLabel genderlblpat;
    private javax.swing.ButtonGroup insurancebtn;
    private javax.swing.JLabel insurancelblpat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup maritalstatusbtn;
    private javax.swing.JLabel maritalstatuslblpat;
    private javax.swing.JRadioButton marriedbtn;
    private javax.swing.JLabel medicalhistorylblpat;
    private javax.swing.JTextField medicalhistorytxtpat;
    public javax.swing.JLabel namelblpat;
    private javax.swing.JCheckBox nobtn;
    private javax.swing.JRadioButton singlebtn;
    private javax.swing.JButton submitbtnpat;
    private javax.swing.JComboBox<String> symptomscbox;
    private javax.swing.JLabel symptomslblpat;
    private javax.swing.JCheckBox yesbtn;
    // End of variables declaration//GEN-END:variables
}
