/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.CityDirectory;
import model.CommunityDirectory;
import model.HospitalDirDirectory;


import model.HospitalDirectory;

import model.HouseDirectory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Ruchi Anand Sagar
 */
public class SystemJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SystemJFrame
     */
    PersonDirectory personHistory;
    PatientDirectory patientHistory;
    HouseDirectory houseHistory;
    CommunityDirectory communityHistory;
    CityDirectory cityHistory;
    HospitalDirectory hospitalHistory;
    HospitalDirDirectory hospitalDirHistory;
    
    
    public SystemJFrame(PersonDirectory personHistory,PatientDirectory patientHistory,HouseDirectory houseHistory,CommunityDirectory communityHistory,  CityDirectory cityHistory,HospitalDirectory hospitalHistory,HospitalDirDirectory hospitalDirHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory=patientHistory;
        this.houseHistory=houseHistory;
        this.communityHistory=communityHistory;
        this.cityHistory=cityHistory;
        this.hospitalHistory=hospitalHistory;
        this.hospitalDirHistory=hospitalDirHistory;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persondetailsbtn = new javax.swing.JButton();
        patientdetailsbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        citybtn = new javax.swing.JButton();
        hospitalbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        persondetailsbtn.setText("Person Details");
        persondetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persondetailsbtnActionPerformed(evt);
            }
        });

        patientdetailsbtn.setText("Patient Details");
        patientdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientdetailsbtnActionPerformed(evt);
            }
        });

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        citybtn.setText("City Details");
        citybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citybtnActionPerformed(evt);
            }
        });

        hospitalbtn.setText("Hospital Details");
        hospitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(citybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(persondetailsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientdetailsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(hospitalbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoutbtn)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persondetailsbtn)
                    .addComponent(patientdetailsbtn))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citybtn)
                    .addComponent(hospitalbtn))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void persondetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persondetailsbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        PersonDirectoryJFrame personDirectoryJFrame=new PersonDirectoryJFrame(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory);
        personDirectoryJFrame.setVisible(true);
    }//GEN-LAST:event_persondetailsbtnActionPerformed

    private void patientdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientdetailsbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        PatientDirectoryJFrame patientDirectoryJFrame=new PatientDirectoryJFrame(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory);
        patientDirectoryJFrame.setVisible(true);
    }//GEN-LAST:event_patientdetailsbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginJFrame loginjframe=new LoginJFrame( personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory);
        loginjframe.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void citybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citybtnActionPerformed
        // TODO add your handling code here:
        dispose();
        CitySystemJFrame cityAdminJFrame=new CitySystemJFrame(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory);
        cityAdminJFrame.setVisible(true);
    }//GEN-LAST:event_citybtnActionPerformed

    private void hospitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        HospitalAdminJFrame hospitalAdminJFrame=new HospitalAdminJFrame(personHistory, patientHistory,houseHistory,communityHistory,cityHistory,hospitalHistory,hospitalDirHistory);
        hospitalAdminJFrame.setVisible(true);
        
    }//GEN-LAST:event_hospitalbtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton citybtn;
    private javax.swing.JButton hospitalbtn;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton patientdetailsbtn;
    private javax.swing.JButton persondetailsbtn;
    // End of variables declaration//GEN-END:variables
}
