/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CityDirectory;
import model.CommunityDirectory;

import model.HospitalDir;
import model.HospitalDirDirectory;
import model.HospitalDirectory;
import model.HouseDirectory;
import model.Patient;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Ruchi Anand Sagar
 */
public class ViewHospitalAdminDJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHospitalAdminDJPanel
     */
  PatientDirectory patientHistory;
    PersonDirectory personHistory;
    HouseDirectory houseHistory;
    CityDirectory cityHistory;
    HospitalDirectory hospitalHistory;
   CommunityDirectory communityHistory;
    HospitalDirDirectory hospitalDirHistory;
    public ViewHospitalAdminDJPanel(PersonDirectory personHistory,PatientDirectory patientHistory,HouseDirectory houseHistory,CommunityDirectory communityHistory,  CityDirectory cityHistory,HospitalDirectory hospitalHistory,HospitalDirDirectory hospitalDirHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory=patientHistory;
        this.houseHistory=houseHistory;
        this.communityHistory=communityHistory;
        this.cityHistory=cityHistory;
        this.hospitalHistory=hospitalHistory;
        this.hospitalDirHistory=hospitalDirHistory;
        populateTableVDoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewhospdoctordetailstbl = new javax.swing.JTable();
        gendervdoclblhos = new javax.swing.JLabel();
        docnamevdoclblhos = new javax.swing.JLabel();
        emailidvdoclblhos = new javax.swing.JLabel();
        experiencevdoclblhos = new javax.swing.JLabel();
        specialityvdoclblhos = new javax.swing.JLabel();
        degreevdoclblhos = new javax.swing.JLabel();
        contactnovdoclblhos = new javax.swing.JLabel();
        namevdoctxthos = new javax.swing.JTextField();
        gendervdoctxthos = new javax.swing.JTextField();
        degreevdoctxthos = new javax.swing.JTextField();
        emailidvdoctxthos = new javax.swing.JTextField();
        experiencevdoctxthos = new javax.swing.JTextField();
        contactnovdoctxthos = new javax.swing.JTextField();
        specialityvdoctxthos = new javax.swing.JTextField();
        updatevdocbtn = new javax.swing.JButton();
        availabilitylbl = new javax.swing.JLabel();
        availibilitytxthos = new javax.swing.JTextField();
        namelblhosp = new javax.swing.JLabel();
        addresslblhosp = new javax.swing.JLabel();
        zipcodelblhosp = new javax.swing.JLabel();
        citylblhosp = new javax.swing.JLabel();
        nametxthosp = new javax.swing.JTextField();
        addresstxthosp = new javax.swing.JTextField();
        citytxthop = new javax.swing.JTextField();
        zipcodetxthosp = new javax.swing.JTextField();

        viewhospdoctordetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Address", "Zip code", "City", "Doctor Name", "Gender", "Email Id", "Contact No", "Degree", "Speciality", "Experience", "Availability"
            }
        ));
        viewhospdoctordetailstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewhospdoctordetailstblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewhospdoctordetailstbl);

        gendervdoclblhos.setText("Gender");

        docnamevdoclblhos.setText("Doctor Name");

        emailidvdoclblhos.setText("Email Id");

        experiencevdoclblhos.setText("Experience");

        specialityvdoclblhos.setText("Speciality");

        degreevdoclblhos.setText("Degree");

        contactnovdoclblhos.setText("Contact No");

        specialityvdoctxthos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityvdoctxthosActionPerformed(evt);
            }
        });

        updatevdocbtn.setText("Update");

        availabilitylbl.setText("Availability");

        namelblhosp.setText("Hospital Name");

        addresslblhosp.setText("Address");

        zipcodelblhosp.setText("ZipCode");

        citylblhosp.setText("City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelblhosp)
                    .addComponent(addresslblhosp)
                    .addComponent(citylblhosp)
                    .addComponent(zipcodelblhosp))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametxthosp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstxthosp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citytxthop, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodetxthosp, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(docnamevdoclblhos)
                        .addGap(26, 26, 26)
                        .addComponent(namevdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contactnovdoclblhos)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatevdocbtn)
                            .addComponent(contactnovdoctxthos)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailidvdoclblhos)
                        .addGap(55, 55, 55)
                        .addComponent(emailidvdoctxthos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gendervdoclblhos)
                        .addGap(59, 59, 59)
                        .addComponent(gendervdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degreevdoclblhos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(experiencevdoclblhos)
                            .addGap(51, 51, 51)
                            .addComponent(experiencevdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(specialityvdoclblhos)
                                .addComponent(availabilitylbl))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(availibilitytxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(specialityvdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(degreevdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(experiencevdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(experiencevdoclblhos))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degreevdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreevdoclblhos))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nametxthosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namelblhosp)
                                    .addComponent(docnamevdoclblhos)
                                    .addComponent(namevdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gendervdoclblhos)
                                    .addComponent(gendervdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addresstxthosp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addresslblhosp))
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citytxthop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citylblhosp)
                            .addComponent(emailidvdoclblhos)
                            .addComponent(emailidvdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zipcodetxthosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zipcodelblhosp))
                                .addGap(230, 230, 230))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contactnovdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactnovdoclblhos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updatevdocbtn)
                                .addGap(90, 90, 90))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialityvdoctxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specialityvdoclblhos))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availibilitytxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availabilitylbl))
                        .addGap(232, 232, 232))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void specialityvdoctxthosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityvdoctxthosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityvdoctxthosActionPerformed

    private void viewhospdoctordetailstblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewhospdoctordetailstblMouseClicked
        // TODO add your handling code here:
        
        int selectedRowIndex=viewhospdoctordetailstbl.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Data not Found");
             return;}
             
          DefaultTableModel model=(DefaultTableModel) viewhospdoctordetailstbl.getModel();
          HospitalDir selectedHospitalDir=(HospitalDir) model.getValueAt(selectedRowIndex, 0);
          
          
          
          namevdoctxthos.setText(selectedHospitalDir.getDocname());
          gendervdoctxthos.setText(selectedHospitalDir.getDocgender());
          emailidvdoctxthos.setText(selectedHospitalDir.getDocemailid());
          contactnovdoctxthos.setText(String.valueOf(selectedHospitalDir.getDoccontactno()));
          degreevdoctxthos.setText(selectedHospitalDir.getDegree());
          specialityvdoctxthos.setText(selectedHospitalDir.getSpeciality());
          experiencevdoctxthos.setText(selectedHospitalDir.getAvailability());
          
          
    }//GEN-LAST:event_viewhospdoctordetailstblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslblhosp;
    private javax.swing.JTextField addresstxthosp;
    private javax.swing.JLabel availabilitylbl;
    private javax.swing.JTextField availibilitytxthos;
    private javax.swing.JLabel citylblhosp;
    private javax.swing.JTextField citytxthop;
    private javax.swing.JLabel contactnovdoclblhos;
    private javax.swing.JTextField contactnovdoctxthos;
    private javax.swing.JLabel degreevdoclblhos;
    private javax.swing.JTextField degreevdoctxthos;
    private javax.swing.JLabel docnamevdoclblhos;
    private javax.swing.JLabel emailidvdoclblhos;
    private javax.swing.JTextField emailidvdoctxthos;
    private javax.swing.JLabel experiencevdoclblhos;
    private javax.swing.JTextField experiencevdoctxthos;
    private javax.swing.JLabel gendervdoclblhos;
    private javax.swing.JTextField gendervdoctxthos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namelblhosp;
    private javax.swing.JTextField nametxthosp;
    private javax.swing.JTextField namevdoctxthos;
    private javax.swing.JLabel specialityvdoclblhos;
    private javax.swing.JTextField specialityvdoctxthos;
    private javax.swing.JButton updatevdocbtn;
    private javax.swing.JTable viewhospdoctordetailstbl;
    private javax.swing.JLabel zipcodelblhosp;
    private javax.swing.JTextField zipcodetxthosp;
    // End of variables declaration//GEN-END:variables

    private void populateTableVDoc() {
        DefaultTableModel model=(DefaultTableModel) viewhospdoctordetailstbl.getModel();
        model.setRowCount(0);
        
        for (HospitalDir hd  : hospitalDirHistory.getHospitalDirHistory())
        {
            Object[] col=new Object[12];
            col[0]= hd;
            col[1]= hd.getHospitaladdress();
            col[2]=hd.getZipcode();
            col[3]=hd.getCity();
            col[4]=hd.getDocname();
            col[5]= hd.getDocgender();
            col[6]= hd.getDocemailid();
            col[7]= hd.getDoccontactno();
            col[8]= hd.getDegree();
            col[9]= hd.getSpeciality();
            col[10]= hd.getExperience();
            col[11]= hd.getAvailability();
            
           
                   
            model.addRow(col);
            
        }
}






}
