/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import javax.swing.JOptionPane;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;


/**
 *
 * @author Ruchi Anand Sagar
 */
public class PatientJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatientJFrame
     */
    PatientDirectory patientHistory;
    PersonDirectory personHistory;
    public PatientJFrame( PersonDirectory personHistory, PatientDirectory patientHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory=patientHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emergencylblpat = new javax.swing.JLabel();
        emailidlblpat = new javax.swing.JLabel();
        emergencytxtpat = new javax.swing.JTextField();
        contactnolblpat = new javax.swing.JLabel();
        medicalhistorylblpat = new javax.swing.JLabel();
        datalblpat = new javax.swing.JLabel();
        symptomslblpat = new javax.swing.JLabel();
        datetxtpat = new javax.swing.JTextField();
        medicalhistorytxtpat = new javax.swing.JTextField();
        maritalstatuslblpat = new javax.swing.JLabel();
        symptomstxtpat = new javax.swing.JTextField();
        maritalstatustxtpat = new javax.swing.JTextField();
        submitbtnpat = new javax.swing.JButton();
        insurancelblpat = new javax.swing.JLabel();
        insurancetxtpat = new javax.swing.JTextField();
        namelblpat = new javax.swing.JLabel();
        allergieslblpat = new javax.swing.JLabel();
        agelblpat = new javax.swing.JLabel();
        allergiestxtpat = new javax.swing.JTextField();
        genderlblpat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder())));

        emergencylblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emergencylblpat.setText("Emergency Contact No");

        emergencytxtpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencytxtpatActionPerformed(evt);
            }
        });

        medicalhistorylblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        medicalhistorylblpat.setText("Medical History");

        datalblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datalblpat.setText("Today's Date");

        symptomslblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        symptomslblpat.setText("Symptoms");

        maritalstatuslblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maritalstatuslblpat.setText("Marital Status");

        submitbtnpat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        submitbtnpat.setText("Submit");
        submitbtnpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnpatActionPerformed(evt);
            }
        });

        insurancelblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insurancelblpat.setText("Health Insurance(If Any)");

        insurancetxtpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insurancetxtpatActionPerformed(evt);
            }
        });

        allergieslblpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allergieslblpat.setText("Any Allergies?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailidlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactnolblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datalblpat)
                                    .addComponent(maritalstatuslblpat)
                                    .addComponent(insurancelblpat)
                                    .addComponent(allergieslblpat)
                                    .addComponent(emergencylblpat)
                                    .addComponent(medicalhistorylblpat)
                                    .addComponent(symptomslblpat))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergiestxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insurancetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maritalstatustxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emergencytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medicalhistorytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(symptomstxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(submitbtnpat)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datalblpat)
                            .addComponent(datetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(agelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(genderlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(maritalstatustxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maritalstatuslblpat))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(emailidlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(insurancetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insurancelblpat))))
                                .addGap(33, 33, 33)
                                .addComponent(contactnolblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(allergieslblpat)
                            .addComponent(allergiestxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emergencylblpat)
                            .addComponent(emergencytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(medicalhistorylblpat))
                    .addComponent(medicalhistorytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(symptomslblpat)
                    .addComponent(symptomstxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(submitbtnpat)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emergencytxtpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencytxtpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencytxtpatActionPerformed

    private void submitbtnpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnpatActionPerformed
        // TODO add your handling code here:
        String name= namelblpat.getText();
        int age= Integer.parseInt(agelblpat.getText());
        String gender= genderlblpat.getText();
        String emailid= emailidlblpat.getText();
        long contactno= Long.parseLong(contactnolblpat.getText());
        String date= datetxtpat.getText();
        String maritalstatus= maritalstatustxtpat.getText();
        String insurance= insurancetxtpat.getText();
        String allergies= allergiestxtpat.getText();
        long emergencycontactno= Long.parseLong(emergencytxtpat.getText());
        String medicalhistory= medicalhistorytxtpat.getText();
        String symptoms= symptomstxtpat.getText();

        Patient pa =patientHistory.addNewPatient();
        pa.setName(name);
        pa.setAge(age);
        pa.setGender(gender);
        pa.setEmailid(emailid);
        pa.setContactno(contactno);
        pa.setTodaysdate(date);
        pa.setMaritalstatus(maritalstatus);
        pa.setInsurance(insurance);
        pa.setAllergies(allergies);
        pa.setEmergencycontact(emergencycontactno);
        pa.setMedicalhistory(medicalhistory);
        pa.setSymptoms(symptoms);
        JOptionPane.showMessageDialog(this, "Registered Successfully!!");

        datetxtpat.setText("");
        maritalstatustxtpat.setText("");
        insurancetxtpat.setText("");
        allergiestxtpat.setText("");
        emergencytxtpat.setText("");
        medicalhistorytxtpat.setText("");
        symptomstxtpat.setText("");
    }//GEN-LAST:event_submitbtnpatActionPerformed

    private void insurancetxtpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insurancetxtpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insurancetxtpatActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel agelblpat;
    private javax.swing.JLabel allergieslblpat;
    private javax.swing.JTextField allergiestxtpat;
    public javax.swing.JLabel contactnolblpat;
    private javax.swing.JLabel datalblpat;
    private javax.swing.JTextField datetxtpat;
    public javax.swing.JLabel emailidlblpat;
    private javax.swing.JLabel emergencylblpat;
    private javax.swing.JTextField emergencytxtpat;
    public javax.swing.JLabel genderlblpat;
    private javax.swing.JLabel insurancelblpat;
    private javax.swing.JTextField insurancetxtpat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maritalstatuslblpat;
    private javax.swing.JTextField maritalstatustxtpat;
    private javax.swing.JLabel medicalhistorylblpat;
    private javax.swing.JTextField medicalhistorytxtpat;
    public javax.swing.JLabel namelblpat;
    private javax.swing.JButton submitbtnpat;
    private javax.swing.JLabel symptomslblpat;
    private javax.swing.JTextField symptomstxtpat;
    // End of variables declaration//GEN-END:variables
}
